language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_install:
  - git submodule update --recursive --init sentinel json-forms

before_script:
  - curl -X PUT localhost:5984/kujua-lite
  - npm install kanso -g
  - kanso push http://localhost:5984/kujua-lite

script: "./scripts/phantom_test.sh http://localhost:5984/kujua-lite"

after_success:
  - if [ "$TRAVIS_BRANCH" != "develop" ]; then exit 0; fi;
  - npm install -g jsontool
  - cat kanso.json | json -o json-4 -e "dependencies[\"kanso-gardener\"] = null; version += \"-alpha.$TRAVIS_BUILD_NUMBER\";" > tmp.json
  - mv tmp.json kanso.json
  - kanso push http://service:a5nghmongP\!@staging.dev.medicmobile.org/markets/alpha/upload

notifications:
  email:
    recipients:
      - dev@medicmobile.org
