language: node_js
node_js:
   - "0.12"
   - "0.10"

services:
  - couchdb

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sleep 3
  - curl -X PUT localhost:5984/medic
  - bash ./scripts/ci/setup.sh
  - npm install kanso -g
  - npm install grunt-cli -g
  - ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update
  - nohup bash -c "./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager start 2>&1 &"

script:
  - node --stack_size=10000 `which grunt` ci
  - cat nohup.out

after_success:
  - python ./scripts/ci/travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeded! Publishing..."
          bash ./scripts/ci/after_success.sh
        else
          echo "Some jobs failed. Not publishing."
        fi
      fi

notifications:
  webhooks: 
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
