# Setting up as a java project allows us to ensure that the JRE/JDK version used
# is actually compatible with webdriver-manager.
language: java
sudo: true
jdk:
  - oraclejdk8

addons:
  firefox: "45.0"

services:
  # docker is used for couchdb 2.0 (not currently available as a travis service)
  - docker

env:
  global:
  - NODE_VERSION=8
  - COUCH_VERSION=2
  - COUCH_URL=http://admin:pass@localhost:5984/medic
  - API_URL=http://admin:pass@localhost:5988
  - COUCH_NODE_NAME=nonode@nohost

install:
  nvm install $NODE_VERSION

before_script:
  - nvm use $NODE_VERSION
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -X PUT localhost:5984/medic
  - bash ./scripts/ci/setup.sh
  - npm install kanso -g
  - npm install grunt-cli -g
  - npm --prefix api install
  - ./node_modules/.bin/webdriver-manager update
  - nohup bash -c "./node_modules/.bin/webdriver-manager start 2>&1 &"
  - until nc -z localhost 4444; do sleep 1; done

script:
  - node --stack_size=10000 `which grunt` ci2
  - cat nohup.out || true

after_success:
  - export $(cat .to_export_back)
  - bash ./scripts/ci/after_success.sh

after_failure:
  - |
    if [ "COUCH_VERSION" = 2 ]; then
      # show the couchdb logs from the docker instance when there was a problem
      docker ps -a
      docker logs couch
    fi

notifications:
  webhooks:
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
