language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_install:
  - git submodule update --recursive --init sentinel json-forms

before_script:
  - curl -X PUT localhost:5984/kujua-lite
  - npm install kanso -g
  - kanso push http://localhost:5984/kujua-lite

script: "./scripts/phantom_test.sh http://localhost:5984/kujua-lite"

after_success:
  - npm install -g jsontool
  - cat kanso.json | json -o json-4 -e "dependencies[\"kanso-gardener\"] = null; version = \"0.3.0-alpha.$TRAVIS_BUILD_NUMBER\";" > tmp.json
  - mv tmp.json kanso.json
  - kanso push http://service:a5nghmongP@medic.iriscouch.com/market/_design/market/_rewrite/upload

notifications:
  email:
    recipients:
      - dev@medicmobile.org
