language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_install:
  - git submodule update --recursive --init sentinel json-forms

before_script:
  - curl -X PUT localhost:5984/kujua-lite
  - npm install kanso -g
  - kanso push http://localhost:5984/kujua-lite

script: "./scripts/phantom_test.sh http://localhost:5984/kujua-lite"

after_success:
  - bash ./scripts/ci/after_success.sh

notifications:
  webhooks: 
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email: false

