language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_install:
  - git submodule update --recursive --init sentinel json-forms

before_script:
  - curl -X PUT localhost:5984/kujua-lite
  - npm install kanso -g
  - kanso push http://localhost:5984/kujua-lite

script: "./scripts/phantom_test.sh http://localhost:5984/kujua-lite"

after_success:
  - sh ./scripts/ci/after_success.sh

notifications:
  email:
    recipients:
      - dev@medicmobile.org
